### ISSUE TITLE
Update to Polymer 2.0

### ISSUE THREAD

**Issue by JosefJezek** [google/uniflow-polymer#11]
Do you plan update UniFlow to Polymer 2.0?

**Comment by militeev** [comment]
Hi Josef,

I'm currently working on other project priorities, so migration to 2.0 is
not in immediate plans.

thanks,
-Andrei

**Comment by urdeveloper** [comment]
@JosefJezek I've forked and updated the code to Polymer 2.0.
https://github.com/urdeveloper/uniflow-polymer/tree/polymer-2

Please feel free to let me know of any issue.

**Comment by urdeveloper** [comment]
#12

**Comment by militeev** [comment]
Thanks urdeveloper, just merged your pull request. 
Version v0.6.0 for Polymer 2.x is available now!
