### ISSUE TITLE
Would it be possible to release a first version

### ISSUE THREAD

**Issue by LostInBrittany** [google/uniflow-polymer#2]
Hi!

After having played a bit with UniFlow, I would like to use it in one of my apps, instead of a similar(-ish) home made redux-like setup.  But in order to use it, I'd like to make the reference in my `bower.json` to point to a defined version, not to the head of the repository.

Would it be possible to put a tag and declare it as an initial version?

**Comment by militeev** [comment]
Done.

**Comment by LostInBrittany** [comment]
Wow, that was fast, **thank you**!!
