### ISSUE TITLE
Making a uniflow version of the Starter Kit app

### ISSUE THREAD

**Issue by LostInBrittany** [google/uniflow-polymer#3]
I often do Polymer courses, workshops and mentoring, both to students and to professional developers, and I've found that most of my students like to use the Polymer Starter Kit as a base in order to build their applications, instead of beginning with an empty project.

I think that having an uniflow based version of the Starter Kit app, with the different elements already in place, would be a great way to introduce the uniflow pattern to Polymer developers.

I had thought about doing it myself, and maybe write an article on it, if it doesn't bother you and if you think it's a good idea.

**Comment by militeev** [comment]
Hi Horacio,

I agree that Polymer Starter Kit is a great starting point. I'd be super excited if Starter Kit is extended to showcase uniflow, and if you're up to this task, that's great! And yes, feel free to spread the word about the library any way you can. If you want me to review your article and/or code, let me know, I'll try to find some time to do that. 

Best of luck!

**Comment by LostInBrittany** [comment]
Hi!

Sorry for the delay, last few weeks have been a bit crazy.

So here you have my version of the polymer Starter kit with UniFlow: https://github.com/LostInBrittany/uniflow-polymer-starter-kit

Please tell me what do you think...

**Comment by LostInBrittany** [comment]
I've added a yeoman generator, https://github.com/LostInBrittany/generator-polymer-init-uniflow-polymer-starter-kit

Now you can use the Uniflow-Polymer-Starter-Kit with Polymer CLI :

1. install  `generator-polymer-init-uniflow-polymer-starter-kit` using npm:
  
      npm install -g generator-polymer-init-uniflow-polymer-starter-kit

1. initialize project from template

  Generate your new project using polymer init:

      mkdir my-app
      cd my-app
      polymer init uniflow-polymer-starter-kit
