### ISSUE TITLE
Sample application

### ISSUE THREAD

**Issue by Mika83AC** [google/uniflow-polymer#5]
Hello militeev,

thank you for your work on UniFlow.

But until now, it's hard for me to understand how all this will and should work together in an application. So may it be possible for you to create a sample application which demonstrates how UniFlow is intended to be used?

Regards,
Michael

**Comment by militeev** [comment]
It's already there: https://github.com/google/uniflow-polymer/tree/master/todomvc!

**Comment by Mika83AC** [comment]
Yes, it is. Thanks militeev.

First I thought "he's talking about a way of building large apps" and then the sample application is a really little app. But that was bullshit, it shows everything i needed to know. :) :+1:
