### ISSUE TITLE
bower polymer-uniflow-a

### ISSUE THREAD

**Issue by Mika83AC** [google/uniflow-polymer#6]
When I'm using UniFlowvia bower (bower install --save polymer-uniflow-a), Chrome gives me errors like "Uncaught ReferenceError: UniFlow is not defined at action-emitter.html:22".

When I download UniFlow from the website as a zip and put it manually in bower_components, everything is fine.

Is there any difference between the download version and the version supplied via bower?

**Comment by militeev** [comment]
Sorry forgot to reply. polymer-uniflow-a is a test repository that shouldn't be used. The only way to properly download correct version is to use GitHub repository path.

**Comment by Mika83AC** [comment]
Ok, thx :)
