### ISSUE TITLE
Support for Polymer 2.0

### ISSUE THREAD

**Issue by elvomka** [google/uniflow-polymer#7]
Any plans to support Polymer 2.0, either via hybrid-mode or directly?

**Comment by militeev** [comment]
We'll discuss it when 2.0 becomes official release (it is still RC). I heard about Polymer team plans to offer built-in solution for data architecture in 2.0 at some point. We will see how it goes.

**Comment by web-padawan** [comment]
@militeev Now when 2.0 is released, do you have any update on this?

**Comment by abdonrd** [comment]
@militeev Polymer team plans to offer built-in solution for data architecture in 2.0? Sounds really interesting!
